
function createNewEntry(path, date, name, alt, priority, type, locationsArray, lighting) {

    return new Promise(resolve => {

        // console.log("START: " + name);
        imgNum = path.split("/")[3];
        // console.log(imgNum);
        database.newEntry(`${path}/${imgNum}`, date, name, alt, priority, type, locationsArray, lighting);
        // console.log("STOP: " + name);
        setTimeout(function () { resolve("complete") }, 10);

    });

}


async function enterNewPictures(pictureInfoArray) {

    for (let i = 0; i < pictureInfoArray.length; i++) {

        await createNewEntry(pictureInfoArray[i][0], pictureInfoArray[i][1], pictureInfoArray[i][2], pictureInfoArray[i][3], pictureInfoArray[i][4], pictureInfoArray[i][5], pictureInfoArray[i][6], pictureInfoArray[i][7]);

    }
    //    console.log("complete");

}


var pictureArray = [
    ["/images/gallery/0", "2021,11,21,6,51,45", "Goblin Valley Bridals 2021", "Groom spinning bride in goblin valley flash shoot", "d", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/1", "2022,4,9,19,43,39", "P and M Sand Dunes Engagements", "Couple holding hands walking down sand dunes", "c", "engagements", ["sand-dunes", "desert", "utah", "california"], "sunset"],
    ["/images/gallery/2", "2022,5,2,18,32,14", "P and A Bridals", "Bride and groom hugging", "c", "bridals", ["antelope-island", "layton", "utah-state-park", "utah"], "sunset"],
    ["/images/gallery/3", "2022,10,16,18,19,42", "H and A Couples Session", "Couple dancing on hiking trail", "c", "couples", ["utah-mountains", "roadside", "fall-trees", "utah"], "cloudy"],
    ["/images/gallery/4", "2023,4,15,10,7,5", "SLC Minis", "Girls running and laughing on a rooftop", "d", "friends", ["salt-lake", "utah"], "full-sun"],
    ["/images/gallery/5", "2022,5,2,18,44,48", "P and A Bridals", "Groom helping bride down rock", "c", "bridals", ["antelope-island", "layton", "utah-state-park", "utah"], "blue-hour"],
    ["/images/gallery/6", "2021,11,21,17,52,39", "Goblin Valley Bridals 2021", "Groom holding bride", "e", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "blue-hour"],
    ["/images/gallery/7", "2021,11,21,18,06,32", "Goblin Valley Bridals 2021", "Groom kissing brides forehead", "b", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "blue-hour"],
    ["/images/gallery/8", "2022,6,23,11,48,33", "Little White Chapel Elopement", "Couple dancing in downtown", "b", "elopements", ["little-white-chapel", "las-vegas", "nevada", "roadside"], "full-sun"],
    ["/images/gallery/9", "2023,4,21,19,3,23", "M Senior April", "Girl laughing in the road", "d", "portraits", ["antelope-island", "roadside", "layton", "utah"], "cloudy"],
    ["/images/gallery/10", "2022,6,23,22,46,38", "Fremont Street Bridals", "Groom kissing bride against wall", "c", "bridals", ["las-vegas-strip", "las-vegas", "nevada", "studio"], "indoor"],
    ["/images/gallery/11", "2022,6,23,22,55,46", "Fremont Street Bridals", "Blurry couple walking away from each other", "d", "bridals", ["las-vegas-strip", "las-vegas", "nevada", "studio"], "indoor"],
    ["/images/gallery/12", "2023,4,21,19,29,28", "M Senior April", "Girl squatting with a soft smile", "d", "portraits", ["antelope-island", "layton", "utah"], "blue-hour"],
    ["/images/gallery/13", "2022,2,4,8,8,46", "City Bridals 2022", "Groom lifting bride in the air", "b", "bridals", ["salt-lake", "downtown", "new-york-rooftop", "new-york-city", "seattle", "utah"], "sunrise"],
    ["/images/gallery/14", "2022,2,4,8,18,8", "City Bridals 2022", "Bride jumping on groom and swinging", "c", "bridals", ["salt-lake", "downtown", "new-york-rooftop", "new-york-city", "seattle", "utah"], "sunrise", "new-york-rooftop"],
    ["/images/gallery/15", "2022,2,4,8,20,43", "City Bridals 2022", "Couple holding hands looking opposite directions", "c", "bridals", ["salt-lake", "downtown", "new-york-rooftop", "new-york-city", "seattle", "utah"], "sunrise"],
    ["/images/gallery/16", "2022,2,4,8,23,41", "City Bridals 2022", "Bride and groom putting their heads and noses together", "d", "bridals", ["salt-lake", "downtown", "new-york-rooftop", "new-york-city", "seattle", "utah"], "sunrise"],
    ["/images/gallery/17", "2022,2,4,8,56,40", "M and E Couple Session", "Couple holding hands and looking at each other", "b", "couples", ["salt-lake", "downtown", "england", "london", "utah"], "sunrise"],
    ["/images/gallery/18", "2022,2,4,9,37,8", "M and E Couple Session", "Guy leaning over girl to kiss her", "c", "couples", ["salt-lake", "new-york", "seattle", "parks", "utah"], "sunrise"],
    ["/images/gallery/19", "2022,2,4,11,5,18", "Snowy Bridals 2022", "Couple walking in the snow on the mountain", "b", "bridals", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "full-sun"],
    ["/images/gallery/20", "2022,2,4,11,15,19", "Snowy Bridals 2022", "Groom lifting bride in the forest", "c", "bridals", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "shaded"],
    ["/images/gallery/21", "2022,2,4,11,33,15", "Snowy Engagements 2022", "Couple playing in the snow", "b", "engagements", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "full-sun"],
    ["/images/gallery/22", "2022,2,4,11,33,50", "Snowy Engagements 2022", "Couple playing in the snow", "b", "engagements", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "full-sun"],
    ["/images/gallery/23", "2022,2,4,11,36,58", "Snowy Engagements 2022", "Couple in the snow lifting girl up", "d", "engagements", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "full-sun"],
    ["/images/gallery/24", "2022,2,4,17,6,48", "L and M Engagements", "Couple sitting and looking at each other", "c", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/25", "2022,2,4,17,8,30", "L and M Engagements", "Couple sitting back to back and looking at each other", "d", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/26", "2022,2,4,17,23,39", "L and M Engagements", "Couple sitting on the ground holding hands", "b", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/27", "2022,2,4,17,57,38", "L and M Engagements", "Girl hugging from behind looking at each other", "c", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/28", "2022,2,4,18,20,49", "P and L Bridals", "Groom lifting bride for a kiss", "b", "elopements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/29", "2022,2,4,19,6,32", "M and T Exit", "Groom kissing brides head", "b", "bridals", ["salt-flats", "salt-lake", "utah"], "blue-hour"],
    ["/images/gallery/30", "2022,10,1,18,37,22", "P and M Bridals", "Bridal couple doing first look by the lake", "b", "bridals", ["utah-lake", "lakes", "utah-county", "utah"], "blue-hour"],
    ["/images/gallery/31", "2022,10,1,18,37,59", "P and M Bridals", "Bride and groom hugging", "a", "bridals", ["utah-lake", "lakes", "utah-county", "utah"], "blue-hour"],
    ["/images/gallery/32", "2022,2,4,19,19,6", "M and T Exit", "Couple in limo drinking champagne", "c", "bridals", ["salt-lake", "limousine", "utah"], "flash"],
    ["/images/gallery/33", "2022,2,4,19,26,40", "M and T Exit", "Couple gazing into each others eyes", "d", "bridals", ["salt-lake", "limousine", "utah"], "flash"],
    ["/images/gallery/34", "2022,2,4,19,32,07", "Salt Flats Wedding Exit", "Bridal couple running to their getaway car with sparklers", "d", "weddings", ["salt-flats", "salt-lake", "utah"], "flash"],
    ["/images/gallery/35", "2022,2,4,19,33,8", "Salt Flats Wedding Exit", "Bridal couple hugging with sparklers", "c", "weddings", ["salt-flats", "salt-lake", "utah"], "flash"],
    ["/images/gallery/36", "2022,2,4,19,36,5", "Salt Flats Wedding Exit", "Groom leaning in to kiss the bride", "d", "weddings", ["salt-flats", "salt-lake", "utah"], "flash"],
    ["/images/gallery/37", "2022,2,4,19,37,18", "Salt Flats Wedding Exit", "Groom and bride laughing", "b", "weddings", ["salt-flats", "salt-lake"], "flash", "utah"],
    ["/images/gallery/38", "2022,10,8,17,11,35", "J and V Couples Session 2022", "Boy holding hand and leading girl", "c", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/39", "2022,3,5,18,20,2", "R Newborn Session", "Couple holding baby and admiring him", "d", "families", ["layton", "studio", "utah"], "indoor"],
    ["/images/gallery/40", "2022,10,8,17,31,43", "B and C Couple Shoot", "Couple sitting down and holding each other and gazing into each others eyes", "c", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/41", "2022,4,9,18,57,22", "P and M Sand Dunes Engagements", "Couple sitting and hugging", "c", "engagements", ["sand-dunes", "desert", "utah"], "sunset"],
    ["/images/gallery/42", "2022,4,9,19,0,37", "P and M Sand Dunes Engagements", "Guy hugging girl from behind and swaying", "b", "engagements", ["sand-dunes", "desert", "utah"], "sunset"],
    ["/images/gallery/43", "2022,4,9,19,1,27", "P and M Sand Dunes Engagements", "Girl being lifted up on guys back", "d", "engagements", ["sand-dunes", "desert", "utah"], "sunset"],
    ["/images/gallery/44", "2023,5,25,19,30,23", "A and K Goblin Valley Bridals", "Guy hugging girl from behind", "b", "bridals", ["goblin-valley", "moab", "desert", "utah"], "cloudy"],
    ["/images/gallery/45", "2023,5,25,20,4,44", "A and K Goblin Valley Bridals", "Bride sitting on rock with groom standing and looking in the distance", "d", "bridals", ["goblin-valley", "moab", "desert", "utah"], "sunset"],
    ["/images/gallery/46", "2023,5,25,20,20,11", "A and K Goblin Valley Bridals", "Groom lifting Bride while admiring each other", "c", "bridals", ["goblin-valley", "moab", "desert", "utah"], "cloudy"],
    ["/images/gallery/47", "2023,5,26,17,4,41", "A and C Arches Engagements", "Guy picking girl up while she kicks her legs back", "b", "engagements", ["arches", "moab", "desert", "utah"], "full-sun"],
    ["/images/gallery/48", "2023,5,26,17,13,14", "A and C Arches Engagements", "Girl hugging guy from behind while they look separate ways", "c", "engagements", ["arches", "moab", "desert", "utah"], "full-sun"],
    ["/images/gallery/49", "2023,5,26,17,36,42", "S and C Arches Bridals", "Couple holding hands and walking while looking down", "b", "bridals", ["arches", "moab", "desert", "utah"], "full-sun"],
    ["/images/gallery/50", "2023,5,26,17,51,49", "S and C Arches Bridals", "Groom kissing side of brides forhead while she looks off into the distance", "c", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/51", "2023,5,26,18,41,11", "S and C Arches Bridals", "Groom holding and looking at bride while she holds her bouquet and looks off into the distance", "b", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/52", "2023,5,26,19,56,48", "M and L Arches Bridals", "Groom kissing brides cheek while holding bouquet", "c", "bridals", ["arches", "moab", "desert", "utah"], "sunset"],
    ["/images/gallery/53", "2023,5,26,19,2,17", "M and L Arches Bridals", "Bride and groom hugging while touching each others foreheads together", "b", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/54", "2023,5,26,19,23,1", "M and L Arches Bridals", "Groom holding brides hand and leading her", "a", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/55", "2023,5,27,6,19,22", "T and L Dead Horse Bridals", "Couple hugging and admiring each other", "c", "bridals", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/56", "2023,5,27,6,30,52", "T and L Dead Horse Bridals", "Couple holding each others hand with groom looking at bride", "a", "bridals", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/57", "2023,5,27,6,34,10", "T and L Dead Horse Bridals", "Groom touching brides chin with bride smiling", "b", "bridals", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/58", "2023,5,27,6,47,13", "T and L Dead Horse Bridals", "Bride and groom holding each other and gazing into each others eyes", "a", "bridals", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/59", "2023,5,13,16,55,6", "G and B Las Vegas Wedding", "Bride and groom looking at each other with bridal party cheering", "a", "weddings", ["las-vegas", "luxury-venue", "nevada"], "shaded"],
    ["/images/gallery/60", "2023,5,13,17,9,12", "G and B Las Vegas Wedding", "Bride and groom forehead to forhead while giggling", "d", "weddings", ["las-vegas", "luxury-venue", "nevada"], "shaded"],
    ["/images/gallery/61", "2023,5,13,17,10,1", "G and B Las Vegas Wedding", "Groom kissing brides forhead while bride is smiling", "c", "weddings", ["las-vegas", "luxury-venue", "nevada"], "shaded"],
    ["/images/gallery/62", "2023,5,13,17,17,29", "G and B Las Vegas Wedding", "Bride and groom jumping in and all white bouncy house", "b", "weddings", ["las-vegas", "luxury-venue", "nevada"], "full-sun"],
    ["/images/gallery/63", "2023,5,13,17,58,30", "G and B Las Vegas Wedding", "Bride and groom dancing", "b", "weddings", ["las-vegas", "luxury-venue", "nevada"], "full-sun"],
    ["/images/gallery/64", "2023,5,21,10,4,40", "E and R Engagements", "Boy chasing girl", "b", "engagements", ["utah-mountains", "fields", "utah"], "full-sun"],
    ["/images/gallery/65", "2021,10,2,17,47,0", "R Portrait Session 2021", "Girl holding neck while looking up and smiling", "e", "portraits", ["eagle-mountain", "utah-county", "utah"], "shaded"],
    ["/images/gallery/66", "2021,10,14,17,8,42", "S Wedding Day", "Bride holding bouque while smiling and looking off into the distance", "c", "weddings", ["this-is-the-place", "salt-lake", "utah"], "cloudy"],
    ["/images/gallery/67", "2021,11,20,8,52,48", "Moab Cozy Engagements 2021", "Couple hugging with boy whispering something funny", "d", "engagements", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/68", "2021,11,21,9,23,8", "A and H Engagements Session", "Guy lifting girl in the air while she lifts her arm up and kicks her leg", "c", "engagements", ["moab", "desert", "roadside", "utah"], "sunrise"],
    ["/images/gallery/69", "2021,11,21,9,22,46", "A and H Engagements Session", "Guy lifting girl up while she has her head and arm up", "b", "engagements", ["moab", "desert", "roadside", "utah"], "sunrise"],
    ["/images/gallery/70", "2022,7,20,6,39,9", "B and S Couples Session", "Couple sitting in grass with boy kissing girls forhead", "b", "couples", ["utah-mountains", "fields", "utah"], "sunrise"],
    ["/images/gallery/71", "2022,10,16,17,55,15", "H and A Couples Session", "Couple sitting with girls legs on guys legs, while they're holding hands and giggling", "d", "couples", ["utah-mountains", "fall-trees", "fields", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/72", "2022,06,23,11,48,28", "Little White Chapel Elopement", "Bride and groom turning towards each other and admiring", "c", "elopements", ["little-white-chapel", "las-vegas", "roadside", "nevada"], "full-sun"],
    ["/images/gallery/73", "2022,6,23,20,41,25", "Bellagio Hotel Bridals", "Couple sitting on the side of a fountain, brides legs are on grooms leg, while they're turned toward each other", "c", "bridals", ["las-vegas-strip", "las-vegas", "italy", "greece", "nevada"], "sunset"],
    ["/images/gallery/74", "2022,6,23,22,54,1", "Fremont Street Bridals", "Groom picking up bride with bride kicking leg back", "e", "bridals", ["las-vegas-strip", "las-vegas", "studio", "nevada"], "indoor"],
    ["/images/gallery/75", "2022,2,4,8,43,43", "M and E Couple Session", "Girl standing on skateboard and kissing boy", "b", "couples", ["salt-lake", "downtown", "new-york-rooftop", "utah"], "sunrise"],
    ["/images/gallery/76", "2022,2,4,9,20,39", "City Bridals 2022", "Bride leading groom across the street while they stare at each other", "d", "bridals", ["salt-lake", "downtown", "roadside", "utah"], "shaded"],
    ["/images/gallery/77", "2022,6,8,15,49,49", "Tibble Fork Paddleboard Lovers", "Guy on back of paddleboard paddling while girl sits infront of him and stares at him", "e", "couples", ["tibble-fork", "utah-county", "lakes", "utah-mountains", "hawaii", "utah"], "cloudy"],
    ["/images/gallery/78", "2023,5,25,20,9,21", "A and K Goblin Valley Bridals", "Groom kissing brides forehead with a veil covering both of their heads", "b", "bridals", ["goblin-valley", "moab", "desert", "utah"], "cloudy"],
    ["/images/gallery/79", "2023,5,26,17,51,43", "S and C Arches Bridals", "Groom pulling bride in while holding bouque down at his side", "c", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/80", "2023,5,26,18,51,52", "M and L Arches Bridals", "Bride and grooms fingertips touching as they pull away from each other", "d", "bridals", ["arches", "moab", "desert", "utah"], "sunset"],
    ["/images/gallery/81", "2023,5,27,6,28,22", "T and L Dead Horse Bridals", "Groom holding bride close while she looks off into the distance", "a", "bridals", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/82", "2023,6,17,11,24,8", "M Family", "Family walking together and looking at each other", "b", "families", ["utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/83", "2023,6,25,20,0,33", "Utah Lake Family 2023", "Couple holding hands with girl also using her other hand to hold his arm", "b", "couples", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/84", "2021,11,20,8,35,56", "Moab Cozy Engagements 2021", "Couple running and holding hands", "c", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "cloudy"],
    ["/images/gallery/85", "2021,11,20,8,47,31", "Moab Cozy Engagements 2021", "Guy hugging girl from behind while they nuzzle into each other", "d", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "shaded"],
    ["/images/gallery/86", "2023,5,25,19,49,13", "A and K Goblin Valley Bridals", "Bride and groom facing each other on a rock", "b", "bridals", ["goblin-valley", "moab", "desert", "utah"], "blue-hour"],
    ["/images/gallery/87", "2023,5,13,17,13,1", "G and B Las Vegas Wedding", "Groom kissing bride's neck", "c", "weddings", ["las-vegas", "luxury-venue", "nevada"], "shaded"],
    ["/images/gallery/88", "2023,5,13,21,37,55", "G and B Las Vegas Wedding", "Bride threw bouquet back", "d", "weddings", ["las-vegas", "luxury-venue", "nevada"], "flash"],
    ["/images/gallery/89", "2023,5,26,17,15,52", "A and C Arches Engagements", "Bride and groom faceing each other and laughing", "b", "engagements", ["arches", "moab", "desert", "utah"], "full-sun"],
    ["/images/gallery/90", "2023,5,26,17,39,57", "A and C Arches Engagements", "Bride and groom kissing with groom dipping bride back", "b", "engagements", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/91", "2023,5,26,17,28,41", "S and C Arches Bridals", "Groom standing behind bride admiring her", "c", "bridals", ["arches", "moab", "desert", "utah"], "full-sun"],
    ["/images/gallery/92", "2023,5,26,17,47,47", "S and C Arches Bridals", "Bride and groom facing each other and dipping", "b", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/93", "2023,5,26,18,40,47", "S and C Arches Bridals", "Bride and groom holding hands and walking uphill", "a", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/94", "2022,8,27,19,14,10", "P and M Mountain Engagements", "Couple hugging, girl grinning", "c", "engagements", ["lehi", "utah-mountains", "forest", "utah-county", "utah"], "sunset"],
    ["/images/gallery/95", "2023,5,26,18,54,14", "M and L Arches Bridals", "Groom leading bride up the rocks", "b", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/96", "2021,11,21,6,42,59", "Goblin Valley Bridals 2021", "Bride and groom looking at and leaning into each other", "d", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/97", "2023,5,26,19,15,32", "M and L Arches Bridals", "Bride lifting dress in the wind and groom hugging in close", "d", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/98", "2023,6,17,11,16,41", "M Family", "Girl looking at boy with wind picking up the girls hair", "b", "couples", ["utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/99", "2022,2,4,9,41,7", "M and E Couple Session", "Boy and girl kissing on a park bench", "b", "couples", ["salt-lake", "new-york", "seattle", "parks", "utah"], "sunrise"],
    ["/images/gallery/100", "2023,6,17,11,27,4", "M Family", "Girl leaning in and whispering in boys ear", "d", "couples", ["utah-mountains", "utah-county", "utah"], "sunset"],
    ["/images/gallery/101", "2023,6,25,20,10,1", "Utah Lake Family 2023", "Boy spinning girl", "c", "couples", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/102", "2023,6,25,20,17,56", "Utah Lake Family 2023", "Sisters petting family dog", "c", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/103", "2023,6,25,20,24,18", "Utah Lake Family 2023", "Family cuddling in close", "a", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/104", "2023,7,13,19,49,57", "M Senior July", "Girl posing in a field", "b", "portraits", ["utah-county", "fields", "utah-mountains", "utah"], "sunset"],
    ["/images/gallery/105", "2023,7,13,19,57,15", "M Senior July", "Girl sitting in flower field", "a", "portraits", ["utah-county", "fields", "utah-mountains", "utah"], "sunset"],
    ["/images/gallery/106", "2023,7,13,20,16,15", "M Senior July", "Girl standing in field looking in the distance", "d", "portraits", ["utah-county", "fields", "utah-mountains", "utah"], "sunset"],
    ["/images/gallery/107", "2023,7,29,14,29,16", "July 2023 SLC Wedding", "Detail shot of items on a table at a wedding", "d", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/108", "2023,7,29,14,44,12", "July 2023 SLC Wedding", "Best man helping groom put jacket on", "e", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/109", "2023,7,29,16,11,26", "July 2023 SLC Wedding", "Father of bride standing facing away from bride waiting for the first look, while a mirror displays the bride in the back", "e", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/110", "2023,7,29,16,36,23", "July 2023 SLC Wedding", "Bride walking down isle", "d", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/111", "2023,8,6,19,45,58", "B and C Engagements", "Girl leading boy with two hands", "b", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/112", "2023,8,6,19,58,21", "B and C Engagements", "Girl and boy hip bumping and laughing", "a", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/113", "2023,8,6,20,6,2", "B and C Engagements", "Couple sitting back to back enjoying the moment", "c", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/114", "2023,8,6,20,14,40", "B and C Engagements", "Boy pulling girl up off her feet while they're back to back", "b", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/115", "2023,8,6,20,16,53", "B and C Engagements", "Couple sitting facing each other with their foreheads touching", "a", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/116", "2023,8,6,20,22,26", "B and C Engagements", "Couple chasing each other and tickling", "a", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/117", "2023,8,6,20,26,21", "B and C Engagements", "Picture of couple from the neck down of them running", "c", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/118", "2023,6,25,20,23,31", "Utah Lake Family 2023", "Family posing in their individual couples", "d", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/119", "2023,6,17,11,7,16", "M Family", "Mom and dad kissing baby's cheek", "c", "families", ["provo", "utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/120", "2021,11,20,18,0,13", "Western Dead Horse Bridals 2021", "Bride and groom kissing with the groom dipping the bride back", "e", "bridals", ["dead-horse", "moab", "desert", "utah"], "sunset"],
    ["/images/gallery/121", "2021,11,20,8,44,10", "Moab Cozy Engagements 2021", "Girl holding guys face and feeling the morning air on their skin", "d", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "sunrise"],
    ["/images/gallery/122", "2021,11,20,8,52,46", "Moab Cozy Engagements 2021", "Boy tickling girls cheek with his nose", "b", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "sunrise"],
    ["/images/gallery/123", "2021,11,21,17,39,39", "Goblin Valley Bridals 2021", "Bride and groom walking while holding hands", "a", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "sunset"],
    ["/images/gallery/124", "2021,11,20,9,4,59", "Moab Cozy Engagements 2021", "Boy picking girl up bridal style and swinging her", "d", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "sunrise"],
    ["/images/gallery/125", "2021,11,20,14,11,37", "Red Rock Bridals 2021", "Groom leading bride up red rocks", "c", "bridals", ["arches", "moab", "desert", "utah", "arizona"], "shaded"],
    ["/images/gallery/126", "2021,11,21,8,21,12", "Dead Horse Lookout 2021", "Scenic view of Dead Horse Lookout Point", "a", "scenery", ["dead-horse", "moab", "desert", "utah"], "sunset"],
    ["/images/gallery/127", "2021,11,21,9,30,10", "A and H Engagements Session", "Girl on guy's shoulders looking down at him", "b", "engagements", ["moab", "desert", "roadside", "utah"], "sunrise"],
    ["/images/gallery/128", "2021,11,21,6,51,46", "Goblin Valley Bridals 2021", "Couple dancing around and holding hands, male looking at female", "a", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/129", "2021,11,21,7,5,24", "Goblin Valley Bridals 2021", "Male holding female's leg up and female hugging", "b", "engagements", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/130", "2021,11,21,7,5,51", "Goblin Valley Bridals 2021", "Couple laughing and walking with arms around eachother", "c", "engagements", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/131", "2021,11,21,7,5,52", "Goblin Valley Bridals 2021", "Groom with arm around bride while she has her leg bent up in the air", "d", "engagements", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/132", "2021,11,21,7,8,35", "Goblin Valley Bridals 2021", "Couple hugging", "a", "engagements", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/133", "2022,6,8,17,37,27", "Provo Canyon Bridals", "Couple sitting in field cuddling in and looking at each other", "d", "bridals", ["provo-canyon", "provo", "orem", "utah-mountains", "fields", "utah"], "cloudy"],
    ["/images/gallery/134", "2022,10,16,17,45,31", "H and A Couples Session", "Couple looking at eachother and petting dog", "c", "couples", ["utah-mountains", "fields", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/135", "2022,6,8,17,41,51", "Provo Canyon Bridals", "Groom picking bride up and laughing", "d", "bridals", ["provo-canyon", "provo", "orem", "utah-mountains", "fields", "utah"], "cloudy"],
    ["/images/gallery/136", "2023,4,15,9,59,35", "SLC Minis", "Girl leaning against cement wall, knee bent foot on wall, holding hair out", "d", "portraits", ["salt-lake", "city", "downtown", "utah"], "full-sun"],
    ["/images/gallery/137", "2022,6,8,17,43,42", "Provo Canyon Bridals", "Couple walking and looking at eachother, girl holding dress while walking", "b", "bridals", ["provo-canyon", "provo", "orem", "utah-mountains", "fields", "utah"], "cloudy"],
    ["/images/gallery/138", "2022,6,8,17,48,52", "Provo Canyon Engagments", "Male leading female down a path, looking at her", "c", "couples", ["provo-canyon", "provo", "orem", "utah-mountains", "fields", "utah"], "cloudy"],
    ["/images/gallery/139", "2022,5,2,18,24,7", "P and A Bridals", "Couple holding rings up at me excidedly", "c", "bridals", ["antelope-island", "layton", "utah-state-park", "utah"], "cloudy"],
    ["/images/gallery/140", "2022,10,16,17,53,22", "H and A Couples Session", "Couple doing bicycle arms while holding both hands toward eachother", "b", "couples", ["utah-mountains", "fields", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/141", "2023,4,15,10,1,2", "SLC Minis", "Girl leaning against cement wall, knee bent foot on wall, holding hair ", "b", "portraits", ["salt-lake", "city", "downtown", "utah"], "full-sun"],
    ["/images/gallery/142", "2023,4,15,10,1,25", "SLC Minis", "Girl leaning against cement wall with knee bent and elbowa supporting on wall", "d", "portraits", ["salt-lake", "city", "downtown", "utah"], "full-sun"],
    ["/images/gallery/143", "2022,10,16,17,55,23", "H and A Couples Session", "Couple sitting in field giggling and cuddling into each other", "b", "couples", ["utah-mountains", "fields", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/144", "2023,4,15,10,1,30", "SLC Minis", "Girl leaning on wall with knee up and looking out", "d", "portraits", ["salt-lake", "city", "downtown", "utah"], "full-sun"],
    ["/images/gallery/145", "2022,10,16,18,14,32", "H and A Couples Session", "Couple hoding hands and walking along the beach looking at eachother", "b", "couples", ["utah-mountains", "lakes", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/146", "2023, 4,15,10,3,21", "SLC Minis", "Girl leaning forward smiling", "c", "portraits", ["salt-lake", "city", "downtown", "utah"], "full-sun"],
    ["/images/gallery/147", "2022,6,8,18,4,57", "Provo Canyon Engagments", "Couple hugging and male picking female up and swaying", "e", "couples", ["provo-canyon", "provo", "orem", "utah-mountains", "fields", "utah"], "cloudy"],
    ["/images/gallery/148", "2023,4,15,10,6,6", "SLC Minis", "Girl has hand on hip and hand in hair and smiling", "c", "portraits", ["salt-lake", "city", "downtown", "utah"], "full-sun"],
    ["/images/gallery/149", "2023,4,15,10,9,42", "SLC Minis", "Three girls walking holding hands and giggling", "c", "friends", ["salt-lake", "city", "downtown", "utah"], "full-sun"],
    ["/images/gallery/150", "2021,11,20,8,34,0", "Moab Cozy Engagements 2021", "Couple holding hands looking at eachother and smiling", "d", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "shaded"],
    ["/images/gallery/151", "2021,11,20,8,34,52", "Moab Cozy Engagements 2021", "Male leading female down a side of a rock wall, looking at her", "c", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "shaded"],
    ["/images/gallery/152", "2022,10,16,18,29,24", "H and A Couples Session", "Couple kissing in front of lake at sunset", "b", "couples", ["utah-mountains", "lakes", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/153", "2022,10,16,18,29,39", "H and A Couples Session", "Male kissing female on the cheek, she is smiling", "c", "couples", ["utah-mountains", "lakes", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/154", "2022,5,2,18,52,59", "P and A Bridals", "Couple spining around holding hands and laughing", "d", "bridals", ["antelope-island", "layton", "utah-state-park", "utah"], "sunset"],
    ["/images/gallery/155", "2022,10,16,18,31,4", "H and A Couples Session", "Male picking female up, swaying and kissing", "e", "couples", ["utah-mountains", "lakes", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/156", "2022,10,16,18,31,1", "H and A Couples Session", "Male leadiing female down the beach, female laughing and grabbing his arm", "d", "couples", ["utah-mountains", "lakes", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/157", "2022,10,16,18,35,11", "H and A Couples Session", "Couple standing with their foreheads togeter and linked arms, with soft smiles", "f", "couples", ["utah-mountains", "lakes", "fall-trees", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/158", "2023,4,15,10,34,58", "SLC Minis", "Girl leaning elbow on column and smiling", "c", "portraits", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/159", "2022,10,23,17,15,43", "Snowy Lovers", "Couple walking and looking at eachother, holding hands", "e", "couples", ["tunnel-springs", "snow", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/160", "2023,4,15,10,37,39", "SLC Minis", "Girl sitting on steps looking in the distance", "d", "portraits", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/161", "2021,11,20,13,52,55", "Red Rock Bridals 2021", "Couple running through the sand holding hands and looking at each other", "c", "bridals", ["arches", "moab", "desert", "utah", "arizona"], "shaded"],
    ["/images/gallery/162", "2023,4,15,10,39,48", "SLC Minis", "Girl sitting on steps, hand in hair", "b", "portraits", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/163", "2023,4,15,10,42,37", "SLC Minis", "3 girls sitting on the steps looking at eachother and laughing", "b", "friends", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/164", "2023,4,15,10,48,10", "SLC Minis", "Girl standing in window sill with hands in her pocket", "c", "portraits", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/165", "2023,04,15,10,49,4", "SLC Minis", "Girl sitting in window, with knee up and soft smile", "a", "portraits", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/166", "2023,4,15,10,49,23", "SLC Minis", "Girl sitting in window, with knee up and soft smile", "c", "portraits", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/167", "2023,4,15,11,30,54", "SLC Minis", "Girl standing with leg poped and arm on hip smiling", "d", "portraits", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/168", "2022,10,23,17,52,18", "Snowy Lovers", "Couple holding hands and female putting her nose on his cheek", "d", "couples", ["tunnel-springs", "snow", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/169", "2023,4,15,11,33,23", "SLC Minis", "Girl standing with both hands on her hips elbows back smiling", "c", "portraits", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/170", "2022,10,23,18,3,42", "Snowy Lovers", "Couple sitting on the path, intertwined together. looking at eachother", "f", "couples", ["tunnel-springs", "snow", "salt-lake", "utah"], "cloudy"],
    ["/images/gallery/171", "2022,10,23,18,3,42", "Snowy Lovers", "Couple honding hands and touching noses while smiling", "e", "couples", ["tunnel-springs", "snow", "salt-lake", "utah"], "cloudy"],
    ["/images/gallery/172", "2021,11,21,17,36,51", "Goblin Valley Bridals 2021", "Groom kissing bride on cheak while holding her waist, bride looking forward", "c", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "sunset"],
    ["/images/gallery/173", "2021,11,21,17,38,16", "Goblin Valley Bridals 2021", "Groom holding bride around the waist, looking down at her. bride looking over her shoulder in the distance", "d", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "sunset"],
    ["/images/gallery/174", "2021,11,21,17,38,55", "Goblin Valley Bridals 2021", "Bride holding grooms hands and leading him, while looking back at him.", "b", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "sunset"],
    ["/images/gallery/175", "2023,4,15,11,51,20", "SLC Minis", "3 girls holding hands laughing while walking down steps", "b", "friends", ["salt-lake", "city", "downtown", "utah"], "shaded"],
    ["/images/gallery/176", "2021,11,21,17,53,18", "Goblin Valley Bridals 2021", "Bride looking down in front of groom, groom looking at her from a far", "a", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "sunset"],
    ["/images/gallery/177", "2021,11,21,17,53,44", "Goblin Valley Bridals 2021", "Bride and groom holding hands, far apart from eachother.", "c", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "sunset"],
    ["/images/gallery/178", "2022,6,22,16,27,31", "Valley Of Fire Engagement", "Couple sitting on rock cuddling, with boy kissing her head", "e", "engagements", ["valley-of-fire", "las-vegas", "nevada", "desert"], "cloudy"],
    ["/images/gallery/179", "2022,6,22,16,27,46", "Valley Of Fire Engagement", "Couple sitting on rock cuddling, girl leaning on boy sideways", "e", "engagements", ["valley-of-fire", "las-vegas", "nevada", "desert"], "cloudy"],
    ["/images/gallery/180", "2022,6,23,11,27,52", "Little White Chapel Elopement", "Couple sitting in the back of the car snuggled in", "c", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "shaded"],
    ["/images/gallery/181", "2022,6,23,11,28,36", "Little White Chapel Elopement", "Couple sitting in the back of the car snuggled in girl has arm around boys neck", "b", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "shaded"],
    ["/images/gallery/182", "2022,6,23,11,37,4", "Little White Chapel Elopement", "Couple standing in front of car nose to nose", "e", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "shaded"],
    ["/images/gallery/183", "2022,6,23,11,38,48", "Little White Chapel Elopement", "Couple standing and cheering with elvis", "d", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "shaded"],
    ["/images/gallery/184", "2022,6,23,11,44,53", "Little White Chapel Elopement", "Couple exiting the chapel, and cheering", "c", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "shaded"],
    ["/images/gallery/185", "2022,5,18,20,3,19", "Lexi Portraits", "Girl standing in front of pompass grass holding brim of hat", "e", "portraits", ["tunnel-springs", "salt-lake", "utah"], "cloudy"],
    ["/images/gallery/186", "2022,6,23,11,50,43", "Little White Chapel Elopement", "Couple running in the streets of las vegas", "f", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "full-sun"],
    ["/images/gallery/187", "2022,6,23,11,59,22", "Little White Chapel Elopement", "Little White Chapel Details", "d", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "shaded"],
    ["/images/gallery/188", "2022,6,23,12,9,55", "Little White Chapel Elopement", "Groom dipping bride and kissing", "f", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/189", "2022,6,23,12,17,15", "Little White Chapel Elopement", "Sitting on chapel bench looking at eachother", "c", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/190", "2022,6,23,12,32,21", "Little White Chapel Elopement", "Sitting on chapel bench kissing with dog on bench", "f", "elopements", ["little-white-chapel", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/191", "2022,6,23,17,43,33", "Paris Hotel Bridals", "Dress details", "c", "weddings", ["las-vegas-strip", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/192", "2022,6,23,18,11,58", "Paris Hotel Bridals", "Brride behinde groom kissing his cheek", "b", "weddings", ["las-vegas-strip", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/193", "2022,6,23,18,12,41", "Paris Hotel Bridals", "Brinde and groom looking into the sun", "c", "weddings", ["las-vegas-strip", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/194", "2022,6,23,19,3,36", "Paris Hotel Bridals", "Groom looking at bride, standing infront of the elevator", "d", "weddings", ["las-vegas-strip", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/195", "2022,6,23,20,9,53", "Beliagio Hotel Bridals", "Groom leading bride down the strip", "c", "elopements", ["las-vegas-strip", "las-vegas", "nevada"], "sunset"],
    ["/images/gallery/196", "2022,6,23,20,18,5", "Beliagio Hotel Bridals", "Groom picking up bride and looking at eachother", "b", "elopements", ["las-vegas-strip", "las-vegas", "nevada"], "sunset"],
    ["/images/gallery/197", "2022,6,23,20,33,30", "Beliagio Hotel Bridals", "Bride laying on grooms lap on the side of the fountain", "b", "elopements", ["las-vegas-strip", "las-vegas", "nevada"], "sunset"],
    ["/images/gallery/198", "2022,6,23,20,43,19", "Beliagio Hotel Bridals", "Couple froliking on the strip ", "c", "elopements", ["las-vegas-strip", "las-vegas", "nevada"], "sunset"],
    ["/images/gallery/199", "2022,6,23,20,49,50", "Beliagio Hotel Bridals", "Bride sitting on the fountain kissing grooms forehead", "f", "elopements", ["las-vegas-strip", "las-vegas", "nevada"], "sunset"],
    ["/images/gallery/200", "2022,6,23,20,52,31", "Beliagio Hotel Bridals", "Bride and groom holding hands, looking at eachother", "c", "elopements", ["las-vegas-strip", "las-vegas", "nevada"], "sunset"],
    ["/images/gallery/201", "2023,4,21,19,2,13", "M Senior April", "Girl squating and smiling in the road", "a", "portraits", ["antelope-island", "roadside", "layton", "utah"], "sunset"],
    ["/images/gallery/202", "2023,4,21,19,3,19", "M Senior April", "Girl holding her hair and tilting head in road", "b", "portraits", ["antelope-island", "roadside", "layton", "utah"], "sunset"],
    ["/images/gallery/203", "2022,6,23,22,17,31", "Fremont Street Bridals", "Kissing with groom holding brides leg up", "d", "bridals", ["las-vegas-strip", "las-vegas", "nevada"], "flash"],
    ["/images/gallery/204", "2022,6,23,22,25,21", "Fremont Street Bridals", "Running through the streets of vegas laughing", "e", "bridals", ["las-vegas-strip", "las-vegas", "nevada"], "flash"],
    ["/images/gallery/205", "2023,4,21,19,7,5", "M Senior April", "Holding hands down with legs crossed, looking in the distance", "c", "portraits", ["antelope-island", "roadside", "layton", "utah"], "sunset"],
    ["/images/gallery/206", "2023,4,21,19,20,3", "M Senior April", "Hand on hip, legs crossed, head tilted, and smiling", "d", "portraits", ["antelope-island", "layton", "utah"], "sunset"],
    ["/images/gallery/207", "2022,6,23,22,47,0", "Fremont Street Bridals", "Groom pushing bride against wall and kisssing", "c", "bridals", ["las-vegas-strip", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/208", "2023,4,21,19,22,0", "M Senior April", "Girl sitting on rock leaning on hand", "d", "portraits", ["antelope-island", "layton", "utah"], "sunset"],
    ["/images/gallery/209", "2023,4,21,19,22,19", "M Senior April", "Girl sitting on rock leaning on hand and smiling", "e", "portraits", ["antelope-island", "layton", "utah"], "sunset"],
    ["/images/gallery/210", "2022,6,23,22,55,45", "Fremont Street Bridals", "Bride and groom walking past eachother", "c", "bridals", ["las-vegas-strip", "las-vegas", "nevada"], "indoor"],
    ["/images/gallery/211", "2022,6,26,19,40,53", "Best Friends Session", "4 girls sitting in a field", "c", "friends", ["tunnel-springs", "fields", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/212", "2022,6,26,19,42,31", "Best Friends Session", "4 girls froliking in field holding hands", "b", "friends", ["tunnel-springs", "fields", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/213", "2022,6,26,20,4,1", "Best Friends Session", "4 girls sitting on fence leaning into eachother", "c", "friends", ["tunnel-springs", "fields", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/214", "2022,6,26,20,4,8", "Best Friends Session", "4 girls sitting on fence looking at eachother and laughing.", "d", "friends", ["tunnel-springs", "fields", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/215", "2022,2,4,8,8,4", "SLC Sunrise Bridals", "Groom holding brides hands from behind her and both smiling at the camera", "e", "bridals", ["salt-lake", "city", "downtown", "utah"], "sunrise"],
    ["/images/gallery/216", "2022,2,4,8,12,2", "SLC Sunrise Bridals", "Couple has noses touching and bride has hand on groom's neck", "d", "bridals", ["salt-lake", "city", "downtown", "utah"], "sunrise"],
    ["/images/gallery/217", "2022,2,4,8,33,58", "SLC Sunrise Bridals", "Groom sitting on the roftop edge and bride leaning agaiinst wall infront of him. ", "g", "bridals", ["salt-lake", "city", "downtown", "utah"], "sunrise"],
    ["/images/gallery/218", "2022,2,4,9,17,12", "M and E Couple Session", "Couple sitting on steps leaning on eachother, male kisssing female's head", "h", "couples", ["salt-lake", "city", "downtown", "utah"], "sunrise"],
    ["/images/gallery/219", "2022,2,4,9,18,44", "SLC Sunrise Bridals", "Couple running down the streets of downtown salt lake city", "b", "bridals", ["salt-lake", "city", "downtown", "roadside", "utah"], "sunrise"],
    ["/images/gallery/220", "2022,2,4,9,20,27", "SLC Sunrise Bridals", "Couple honlding hands and looking at eachother, with some distance between them", "f", "bridals", ["salt-lake", "city", "downtown", "roadside", "utah"], "sunrise"],
    ["/images/gallery/221", "2022,2,4,9,40,7", "M and E Couple Session", "Couple on park bench, girl has both legs over the boy's legs, he is kissing her forehead.", "b", "couples", ["salt-lake", "city", "downtown", "parks", "utah"], "sunrise"],
    ["/images/gallery/222", "2022,2,4,9,40,37", "M and E Couple Session", "Couple on park bench, girl has both legs over the boy's legs.", "e", "couples", ["salt-lake", "city", "downtown", "parks", "utah"], "sunrise"],
    ["/images/gallery/223", "2022,2,4,11,17,37", "Snowy Bridals 2022", "Couple in the snow kissing with groom's hands on bride's face", "d", "bridals", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "shaded"],
    ["/images/gallery/224", "2022,2,4,11,28,37", "Snowy Engagements 2022", "Has nose to nose and smiling under a blanket", "f", "couples", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "shaded"],
    ["/images/gallery/225", "2022,2,4,11,37,8", "Snowy Engagements 2022", "Male huggung girl from behind and holding hand, while looking at her. ", "d", "couples", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "full-sun"],
    ["/images/gallery/226", "2022,2,4,11,44,39", "Snowy Engagements 2022", "Girl holding boys' arm and hand while smiling srait at the camera", "c", "couples", ["salt-lake", "utah-mountains", "forest", "snow", "utah"], "sunset"],
    ["/images/gallery/227", "2022,8,27,18,49,34", "P and M Mountain Engagements", "Couple holding hands and smiling with boy laying his head on hers", "e", "engagements", ["lehi", "utah-mountains", "fields", "utah-county", "utah"], "sunset"],
    ["/images/gallery/228", "2022,8,27,18,53,2", "P and M Mountain Engagements", "Couple holding hands far apart while walking down hill", "d", "engagements", ["lehi", "utah-mountains", "fields", "utah-county", "utah"], "sunset"],
    ["/images/gallery/229", "2022,8,27,18,55,12", "P and M Mountain Engagements", "Male sitting on rock looking back at female as she hugs him and kisses him on the cheek", "b", "engagements", ["lehi", "utah-mountains", "fields", "utah-county", "utah"], "sunset"],
    ["/images/gallery/230", "2022,8,27,17,56,42", "P and M Mountain Engagements", "Girl on boy's shoulders and looking down at him", "c", "engagements", ["lehi", "utah-mountains", "fields", "utah-county", "utah"], "sunset"],
    ["/images/gallery/231", "2022,8,27,19,17,51", "P and M Mountain Engagements", "Boy swinging girl and both laughing together", "d", "engagements", ["lehi", "utah-mountains", "fields", "utah-county", "utah"], "sunset"],
    ["/images/gallery/232", "2022,2,4,17,27,17", "L and M Engagements", "Couple holding pinkies", "c", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/233", "2022,2,4,17,51,7", "L and M Engagements", "Couple laying down and have a hand on eachothers faces, serious faces.", "a", "engagements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/234", "2022,9,23,6,58,10", "Jubeck Family", "Family turned in towards eachother and holding their significant others arm or hand", "d", "families", ["salt-lake", "utah-mountains", "forest", "utah"], "sunrise"],
    ["/images/gallery/235", "2022,9,23,6,58,34", "Jubeck Family", "Family turned in towards eachother and holding their significant others arm or hand", "a", "families", ["salt-lake", "utah-mountains", "forest", "utah"], "sunrise"],
    ["/images/gallery/236", "2022,9,23,7,5,16", "Jubeck Family", "Family turned in towards eachother and holding their significant others arm or hand", "d", "families", ["salt-lake", "utah-mountains", "forest", "lakes", "utah"], "sunrise"],
    ["/images/gallery/237", "2022,2,4,18,18,23", "P and L Bridals", "Female leaning on male closing her eyes and has arm around the back of his neck", "d", "elopements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/238", "2022,2,4,18,19,56", "P and L Bridals", "Male picking up female and dipping her. nose to nose, and smiling", "b", "elopements", ["salt-flats", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/239", "2022,9,23,7,28,49", "Jubeck Family", "Couple walking down path holding hands", "e", "families", ["salt-lake", "utah-mountains", "forest", "utah"], "sunrise"],
    ["/images/gallery/240", "2022,9,23,7,35,39", "Jubeck Family", "Family sitting on bench leaning into eachother", "a", "families", ["salt-lake", "utah-mountains", "forest", "lakes", "utah"], "sunrise"],
    ["/images/gallery/241", "2022,9,23,7,36,50", "Jubeck Family", "Family turning towards eachother and smiling forward", "f", "families", ["salt-lake", "utah-mountains", "forest", "lakes", "utah"], "sunrise"],
    ["/images/gallery/242", "2022,10,1,18,45,12", "P and M Bridals", "Bride behind groom smiling at eachother", "c", "bridals", ["utah-lake", "lakes", "utah-county", "utah"], "sunset"],
    ["/images/gallery/243", "2022,10,1,18,46,43", "P and M Bridals", "Groom picking up bride and looking at eachother", "e", "bridals", ["utah-lake", "lakes", "utah-county", "utah"], "sunset"],
    ["/images/gallery/244", "2023,4,1,17,24,15", "Lexi Graduation Session", "Girl has one arm around and one arm touching face", "d", "portraits", ["lehi", "snow", "forest", "utah-mountains", "utah"], "cloudy"],
    ["/images/gallery/245", "2023,4,1,17,30,58", "Lexi Graduation Session", "Girl holding grad cap by her side and smiling", "e", "portraits", ["lehi", "snow", "forest", "utah-mountains", "utah"], "cloudy"],
    ["/images/gallery/246", "2022,10,8,17,4,44", "J and V Couples Session 2022", "Couple nose to nose and forehead to forehead", "f", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/247", "2022,3,5,18,1,10", "R Newborn Session", "Dad holding baby out in arms", "c", "families", ["layton", "studio", "utah"], "indoor"],
    ["/images/gallery/248", "2022,3,5,18,3,8", "R Newborn Session", "Dad holding baby on cheast, baby laying on shoulder", "d", "families", ["layton", "studio", "utah"], "indoor"],
    ["/images/gallery/249", "2023,4,1,19,8,12", "Lexi Graduation Session", "Girl standing, smiling, while holding her hair back with one hand", "f", "portraits", ["utah-lake", "lakes", "utah-county", "utah"], "cloudy"],
    ["/images/gallery/250", "2022,10,8,17,12,18", "J and V Couples Session 2022", "Couple kissing and holding hands standig and facing eachother", "f", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/251", "2022,6,8,14,2,52", "Summer Adventure Couples Session", "Couple holding hands apart from eachother and looking at eachother", "d", "couples", ["lehi", "fields", "forest", "utah-mountains", "utah"], "full-sun"],
    ["/images/gallery/252", "2022,10,8,17,20,9", "J and V Couples Session 2022", "Girl sitting on bridge, guy holding her. forehead to forehead, nose to nose", "f", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/253", "2022,3,5,18,19,51", "R Newborn Session", "Couple snuggling on couch looking down at baby", "d", "families", ["layton", "studio", "utah"], "indoor"],
    ["/images/gallery/254", "2022,10,8,17,22,8", "J and V Couples Session 2022", "Couple hugging", "e", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/255", "2022,6,8,14,15,4", "Summer Adventure Couples Session", "Couple holding both hands and looking at eachother", "d", "couples", ["lehi", "fields", "forest", "utah-mountains", "utah"], "full-sun"],
    ["/images/gallery/256", "2022,10,8,17,29,5", "B and C Couple Shoot", "Couple holding hands and walking forward", "e", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/257", "2022,3,5,18,35,15", "R Newborn Session", "Baby sleeping on bed", "c", "families", ["layton", "studio", "utah"], "indoor"],
    ["/images/gallery/258", "2022,10,8,17,35,20", "B and C Couple Shoot", "Girl on top of rock, hugging guy from behind ", "d", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/259", "2022,4,9,18,50,43", "P and M Sand Dunes Engagements", "Guy has hands on girl's face, nose to nose with eyes closed", "e", "engagements", ["sand-dunes", "desert", "utah"], "sunset"],
    ["/images/gallery/260", "2022,6,8,14,40,6", "Summer Content Day", "Guy dipping girl down a little, looking at eachother with their foreheads together", "e", "couples", ["lehi", "forest", "roadside", "utah-mountains", "utah"], "full-sun"],
    ["/images/gallery/261", "2022,3,5,18,43,9", "R Newborn Session", "Parents holding baby's hand with fingertip", "d", "families", ["layton", "studio", "utah"], "indoor"],
    ["/images/gallery/262", "2022,10,8,17,43,59", "Fall Minis 2022", "Couple holding hands and looking at eachother", "f", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/263", "2023,4,1,19,21,59", "Lexi Graduation Session", "Girl laughing in cap and gown", "d", "portraits", ["utah-lake", "lakes", "utah-county", "utah"], "cloudy"],
    ["/images/gallery/264", "2022,6,8,14,41,41", "Summer Content Day", "Guy picking up girl as she kicks her legs", "f", "couples", ["lehi", "forest", "roadside", "utah-mountains", "utah"], "full-sun"],
    ["/images/gallery/265", "2022,3,5,18,55,8", "R Newborn Session", "Parents cuddling baby, baby looking up at them", "d", "families", ["layton", "studio", "utah"], "indoor"],
    ["/images/gallery/266", "2022,6,8,14,51,59", "Summer Content Day", "Guy holding girl from behind both looking out to the lake", "e", "couples", ["lehi", "forest", "utah-mountains", "utah"], "shaded"],
    ["/images/gallery/267", "2022,10,8,17,45,0", "Fall Minis 2022", "Couple kissing, close up picture", "d", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/268", "2022,4,9,19,1,22", "P and M Sand Dunes Engagements", "Guy lifting girl on his back and leaning over", "c", "engagements", ["sand-dunes", "desert", "utah"], "sunset"],
    ["/images/gallery/269", "2023,4,1,19,25,57", "Lexi Graduation Session", "Girl folding her arm, looking over her shoulder and smiling", "d", "portraits", ["utah-lake", "lakes", "utah-county", "utah"], "cloudy"],
    ["/images/gallery/270", "2022,10,8,17,58,27", "Fall Minis 2022", "Couple sitting facing eachother, her legs over top of his", "e", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/271", "2022,6,8,15,4,24", "Summer Content Day", "Guy helping girl walk across log", "c", "couples", ["lehi", "forest", "utah-mountains", "utah"], "shaded"],
    ["/images/gallery/272", "2022,10,8,17,51,41", "Fall Minis 2022", "Guy spinning girl ", "d", "couples", ["utah-mountains", "fall-trees", "forest", "utah"], "cloudy"],
    ["/images/gallery/273", "2023,4,1,19,26,10", "Lexi Graduation Session", "Girl has one arm on stomach and one hand on chin looking out", "f", "portraits", ["utah-lake", "lakes", "utah-county", "utah"], "cloudy"],
    ["/images/gallery/274", "2023,4,1,19,27,4", "Lexi Graduation Session", "Girl kicking leg out, arm out, and one hand pushing back hair", "b", "portraits", ["utah-lake", "lakes", "utah-county", "utah"], "cloudy"],
    ["/images/gallery/275", "2022,6,8,15,45,30", "Tibble Fork Paddleboard Lovers", "Couple paddleboarding ", "c", "couples", ["tibble-fork", "utah-county", "lakes", "utah-mountains", "hawaii", "utah"], "cloudy"],
    ["/images/gallery/276", "2022,6,8,15,46,46", "Tibble Fork Paddleboard Lovers", "Couple standing on paddle boards, holding hands, and kissing", "e", "couples", ["tibble-fork", "utah-county", "lakes", "utah-mountains", "hawaii", "utah"], "cloudy"],
    ["/images/gallery/277", "2022,6,8,17,13,10", "Provo Bridal Session", "Guy lifting girl and kissing", "f", "bridals", ["provo", "fields", "utah-county", "utah-mountains", "utah"], "cloudy"],
    ["/images/gallery/278", "2022,10,16,17,38,26", "H and A Couples Session", "Girl holding guys' arm, guy holding the dog on a leash", "f", "couples", ["utah-mountains", "fall-trees", "fields", "utah-county", "lehi", "utah"], "sunset"],
    ["/images/gallery/279", "2021,11,21,7,0,0", "Goblin Valley Bridals 2021", "Guy has flower in mouth girl holding flowers and laughing while they are hugging", "a", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/280", "2023,6,25,20,13,28", "Utah Lake Family 2023", "Guy spinning girl while looking at her", "c", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/281", "2023,6,25,20,18,45", "Utah Lake Family 2023", "4 sisters looking at eachother and laughing holding the leash of their dog", "d", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/282", "2023,6,25,20,22,12", "Utah Lake Family 2023", "Family walking forward and looking at eachother", "c", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/283", "2023,6,25,20,27,15", "Utah Lake Family 2023", "4 sisters leaning into eachother and smiling", "b", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/284", "2023,7,13,19,56,10", "Maren Senior Pictures", "Girl sitting in flower field one knee up with arm resting on it, other hand touching her cheek, and smiling", "f", "portraits", ["provo", "forest", "utah-county", "utah"], "sunset"],
    ["/images/gallery/285", "2023,7,13,19,58,57", "Maren Senior Pictures", "Girl laughing and swaying her arm, one arm on hip", "c", "portraits", ["provo", "forest", "utah-county", "utah"], "sunset"],
    ["/images/gallery/286", "2023,7,13,20,6,41", "Maren Senior Pictures", "Girl laughing and leaning forward ", "b", "portraits", ["provo", "forest", "utah-county", "utah"], "sunset"],
    ["/images/gallery/287", "2023,7,29,14,34,37", "July 2023 SLC Wedding", "Wedding venue", "d", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/288", "2023,7,29,14,36,44", "July 2023 SLC Wedding", "Groom getting ready", "e", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/289", "2023,7,29,15,6,25", "July 2023 SLC Wedding", "Dress details", "e", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/290", "2023,5,26,17,17,56", "A and C Arches Engagements", "Guy has his hands on her face, she has her hands around his waist. looking at eachother", "d", "engagements", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/291", "2023,5,26,17,21,0", "A and C Arches Engagements", "Couple holding hands and walking forward", "c", "engagements", ["arches", "moab", "desert", "utah"], "full-sun"],
    ["/images/gallery/292", "2023,7,29,15,35,36", "July 2023 SLC Wedding", "Bride getting ready before the ceramony ", "f", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/293", "2023,7,29,15,51,15", "July 2023 SLC Wedding", "Flower details", "g", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/294", "2023,7,29,15,53,6", "July 2023 SLC Wedding", "Bar details", "e", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/295", "2023,5,26,17,41,36", "A and C Arches Engagements", "Guy hugging from behind girl laughing and lifting her leg", "d", "engagements", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/296", "2023,5,26,17,43,4", "A and C Arches Engagements", "Guy helping girl down the rock, she is fixing her hair from the wind", "d", "engagements", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/297", "2023,7,29,16,48,39", "July 2023 SLC Wedding", "Bride and groom walking back down the isle", "g", "weddings", ["salt-lake", "luxury-venue", "utah"], "indoor"],
    ["/images/gallery/298", "2023,5,26,18,45,19", "M and L Arches Bridals", "Bride and groom standing towards eachother with their foreheads and noses together", "c", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/299", "2023,5,26,18,48,17", "M and L Arches Bridals", "Bride and groom walking while holding hands up the sand hill", "f", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/300", "2023,5,26,19,6,23", "M and L Arches Bridals", "Couple on top of rock with their faces close, landscape", "d", "bridals", ["arches", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/301", "2023,5,27,7,22,15", "Dead Horse Point Picnic", "Couple kissing while holding eachother", "b", "couples", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/302", "2023,5,27,7,35,14", "Dead Horse Point Picnic", "Guy hugging girl from behind and she is holding his arms", "c", "couples", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/303", "2023,5,27,7,47,29", "Dead Horse Point Picnic", "Couple sitting on blanket kissing while holding muffins", "e", "couples", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/304", "2023,5,27,7,51,43", "Dead Horse Point Picnic", "Couple sitting on blanket kissing ", "c", "couples", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/305", "2023,8,20,7,34,7", "K and A Maturnity Session", "Couple holding hands and looking at eachother, mom is holding her belly", "d", "families", ["ogden", "fields", "utah"], "cloudy"],
    ["/images/gallery/306", "2023,5,27,7,56,16", "Dead Horse Point Picnic", "Couple sitting on blanket holding their muffins to show eachother", "e", "couples", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/307", "2023,8,20,7,37,55", "K and A Maturnity Session", "Mom looking back at dad, dad is smiling", "b", "families", ["ogden", "fields", "utah"], "cloudy"],
    ["/images/gallery/308", "2023,8,20,7,50,39", "K and A Maturnity Session", "Mom looking back at dad, leading him in the field", "c", "families", ["ogden", "fields", "utah"], "cloudy"],
    ["/images/gallery/309", "2023,8,20,7,50,39", "K and A Maturnity Session", "Mom and dad sitting faces close together", "e", "families", ["ogden", "fields", "utah"], "cloudy"],
    ["/images/gallery/310", "2023,8,20,7,52,59", "K and A Maturnity Session", "Mom and dad sitting and looking down at belly", "c", "families", ["ogden", "fields", "utah"], "cloudy"],
    ["/images/gallery/311", "2023,8,20,7,54,39", "K and A Maturnity Session", "Dad kissing mom on the neck, both have a hand on her belly", "f", "families", ["ogden", "fields", "utah"], "cloudy"],
    ["/images/gallery/312", "2023,5,27,8,9,15", "Dead Horse Point Picnic", "Couple laying on the ground kissing", "d", "couples", ["dead-horse", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/313", "2023,8,20,7,56,55", "K and A Maturnity Session", "Dad holding mom's belly while turned into eachother", "f", "families", ["ogden", "fields", "utah"], "cloudy"],
    ["/images/gallery/314", "2023,5,27,8,13,6", "Dead Horse Point Picnic", "Girl over guy on the ground, takiing a polaroid", "d", "couples", ["dead-horse", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/315", "2023,8,25,19,28,50", "B and K Bridals", "Couple holding hands, standing nose to nose with eyes closed", "e", "bridals", ["utah-mountains", "forest", "utah"], "sunset"],
    ["/images/gallery/316", "2023,8,25,19,33,4", "B and K Bridals", "Bride leaning on groom's shoulder, smiling and looking up at him", "f", "bridals", ["utah-mountains", "forest", "utah"], "sunset"],
    ["/images/gallery/317", "2023,5,27,8,21,18", "Dead Horse Point Picnic", "Couple looking up to the sky on the ground, with their cheeks together holding eachothers faces with eyes closed", "c", "couples", ["dead-horse", "moab", "desert", "utah"], "shaded"],
    ["/images/gallery/318", "2023,8,25,19,35,18", "B and K Bridals", "Couple holding hands and side. Looking at eachother and smiling", "b", "bridals", ["utah-mountains", "forest", "utah"], "sunset"],
    ["/images/gallery/319", "2023,8,25,19,39,8", "B and K Bridals", "Groom has hand around bride's waist, bride is holding her dress as they walk out ", "a", "bridals", ["utah-mountains", "forest", "utah"], "sunset"],
    ["/images/gallery/320", "2023,5,27,8,27,55", "Dead Horse Point Picnic", "Guy hugging girl from behind and swaying", "f", "couples", ["dead-horse", "moab", "desert", "utah"], "sunrise"],
    ["/images/gallery/321", "2023,6,17,10,58,46", "M Family", "Dad holding baby and looking at him, mom had hand on baby and looking down", "d", "families", ["provo", "utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/322", "2023,6,17,10,59,22", "M Family", "Dad holding baby and looking at him, mom holding his hand and looking at baby. ", "c", "families", ["provo", "utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/323", "2023,6,17,11,18,42", "M Family", "Guy kissing her neck while holding her waist", "b", "couples", ["provo", "utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/324", "2023,6,17,11,19,42", "M Family", "Couple kissing while holding hands", "e", "couples", ["provo", "utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/325", "2023,6,17,11,25,26", "M Family", "Couple walking while holding hands, guy looking back at girl", "d", "couples", ["provo", "utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/326", "2023,6,17,11,27,0", "M Family", "Couple about to kiss, girl has hands on boy's face", "e", "couples", ["provo", "utah-mountains", "utah-county", "utah"], "full-sun"],
    ["/images/gallery/327", "2023,6,25,20,0,26", "Utah Lake Family 2023", "Couple looking straight ahead, girl holding boy's arm while holding hands", "b", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/328", "2023,6,25,20,7,18", "Utah Lake Family 2023", "Couple holding hands and walking forward looking at eachother", "e", "families", ["utah-lake", "utah-county", "lakes", "utah"], "sunset"],
    ["/images/gallery/329", "2023,8,25,19,55,21", "B and K Bridals", "Bride holding groom in close with his jacket, nose to nose close up", "d", "bridals", ["utah-mountains", "forest", "utah"], "sunset"],
    ["/images/gallery/330", "2023,8,25,19,56,4", "B and K Bridals", "Groom dipping bride a little and smiling", "f", "bridals", ["utah-mountains", "forest", "utah"], "sunset"],
    ["/images/gallery/331", "2021,11,21,6,59,0", "Goblin Valley Bridals 2021", "Groom has flower in his mouth and smiling, bride is laughing into him and holding a flower bouqet in her hands", "b", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "flash"],
    ["/images/gallery/332", "2021,11,21,12,0,0", "Goblin Valley Bridals 2021", "Bride and groom walking in the desert holding hands far apart", "a", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "sunset"],
    ["/images/gallery/333", "2021,11,21,12,1,0", "Goblin Valley Bridals 2021", "Bride and groom wlaking, groom spinning bride as she walks", "d", "bridals", ["goblin-valley", "moab", "desert", "utah", "arizona"], "sunset"],
    ["/images/gallery/334", "2021,11,20,8,35,0", "Moab Cozy Engagements 2021", "Girl holding both of her hands on his hand, smiling at eachother. ", "c", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "sunrise"],
    ["/images/gallery/335", "2021,11,20,8,36,0", "Moab Cozy Engagements 2021", "Couple holding hands far apart on top of a rock", "e", "engagements", ["arches", "moab", "desert", "utah", "arizona"], "sunrise"],
    ["/images/gallery/336", "2022,5,18,19,20,58", "Lexi Portraits", "Girl holding the brim of her hat with both hands, looking to the side", "e", "portraits", ["tunnel-springs", "fields", "salt-lake", "utah"], "sunset"],
    ["/images/gallery/337", "2022,6,10,13,9,35", "S and K Wedding Day", "Bridal party leaning in together and smiling", "c", "weddings", ["luxury-venue", "salt-lake", "utah"], "indoor"],
    ["/images/gallery/338", "2022,7,20,5,56,45", "B and S Couples Session", "Walking down path and laughing, while holding hands and bumping into eachother", "d", "couples", ["utah-mountains", "fields", "forest", "utah"], "sunset"]
];

// ["/images/gallery/", "date", "name", "alt", "priority", "type", ["locations"], "lighting"]

setTimeout(function () {
    console.log("started");
    enterNewPictures(pictureArray);
}, 500);
